### ISSUE TITLE
Generalize fdists

### ISSUE THREAD

**Issue by Tragicus** [affeldt-aist/infotheo#99]
fdists are currently defined over the R type of the standard library. Some developments would like to rely on this library but use structures from the mathcomp library. So we would like to have them generalized (maybe to numFieldType).

**Comment by affeldt-aist** [comment]
Indeed, with a generalization akin to this one:
https://github.com/affeldt-aist/trajectories/blob/d4da32f8ca7dbff1ad8ef1aafa5071dba5218d6a/theories/hulls.v#L16-L45

**Comment by affeldt-aist** [comment]
PR #103 does that and should be merged very soon into master.
